// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multimsg.proto

package com.dragon.proto.message;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:multimessage.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.multimessage.Message.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.multimessage.Message.Type type = 1;</code>
     */
    com.dragon.proto.message.Messages.Message.Type getType();

    /**
     * <code>.multimessage.Foo foo = 2;</code>
     */
    boolean hasFoo();
    /**
     * <code>.multimessage.Foo foo = 2;</code>
     */
    com.dragon.proto.message.Messages.Foo getFoo();
    /**
     * <code>.multimessage.Foo foo = 2;</code>
     */
    com.dragon.proto.message.Messages.FooOrBuilder getFooOrBuilder();

    /**
     * <code>.multimessage.Bar bar = 3;</code>
     */
    boolean hasBar();
    /**
     * <code>.multimessage.Bar bar = 3;</code>
     */
    com.dragon.proto.message.Messages.Bar getBar();
    /**
     * <code>.multimessage.Bar bar = 3;</code>
     */
    com.dragon.proto.message.Messages.BarOrBuilder getBarOrBuilder();

    /**
     * <code>.multimessage.Baz baz = 4;</code>
     */
    boolean hasBaz();
    /**
     * <code>.multimessage.Baz baz = 4;</code>
     */
    com.dragon.proto.message.Messages.Baz getBaz();
    /**
     * <code>.multimessage.Baz baz = 4;</code>
     */
    com.dragon.proto.message.Messages.BazOrBuilder getBazOrBuilder();
  }
  /**
   * Protobuf type {@code multimessage.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:multimessage.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              com.dragon.proto.message.Messages.Foo.Builder subBuilder = null;
              if (foo_ != null) {
                subBuilder = foo_.toBuilder();
              }
              foo_ = input.readMessage(com.dragon.proto.message.Messages.Foo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(foo_);
                foo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.dragon.proto.message.Messages.Bar.Builder subBuilder = null;
              if (bar_ != null) {
                subBuilder = bar_.toBuilder();
              }
              bar_ = input.readMessage(com.dragon.proto.message.Messages.Bar.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bar_);
                bar_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.dragon.proto.message.Messages.Baz.Builder subBuilder = null;
              if (baz_ != null) {
                subBuilder = baz_.toBuilder();
              }
              baz_ = input.readMessage(com.dragon.proto.message.Messages.Baz.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baz_);
                baz_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dragon.proto.message.Messages.internal_static_multimessage_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dragon.proto.message.Messages.internal_static_multimessage_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dragon.proto.message.Messages.Message.class, com.dragon.proto.message.Messages.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code multimessage.Message.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FOO = 0;</code>
       */
      FOO(0),
      /**
       * <code>BAR = 1;</code>
       */
      BAR(1),
      /**
       * <code>BAZ = 2;</code>
       */
      BAZ(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FOO = 0;</code>
       */
      public static final int FOO_VALUE = 0;
      /**
       * <code>BAR = 1;</code>
       */
      public static final int BAR_VALUE = 1;
      /**
       * <code>BAZ = 2;</code>
       */
      public static final int BAZ_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return FOO;
          case 1: return BAR;
          case 2: return BAZ;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.dragon.proto.message.Messages.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:multimessage.Message.Type)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.multimessage.Message.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.multimessage.Message.Type type = 1;</code>
     */
    public com.dragon.proto.message.Messages.Message.Type getType() {
      com.dragon.proto.message.Messages.Message.Type result = com.dragon.proto.message.Messages.Message.Type.valueOf(type_);
      return result == null ? com.dragon.proto.message.Messages.Message.Type.UNRECOGNIZED : result;
    }

    public static final int FOO_FIELD_NUMBER = 2;
    private com.dragon.proto.message.Messages.Foo foo_;
    /**
     * <code>.multimessage.Foo foo = 2;</code>
     */
    public boolean hasFoo() {
      return foo_ != null;
    }
    /**
     * <code>.multimessage.Foo foo = 2;</code>
     */
    public com.dragon.proto.message.Messages.Foo getFoo() {
      return foo_ == null ? com.dragon.proto.message.Messages.Foo.getDefaultInstance() : foo_;
    }
    /**
     * <code>.multimessage.Foo foo = 2;</code>
     */
    public com.dragon.proto.message.Messages.FooOrBuilder getFooOrBuilder() {
      return getFoo();
    }

    public static final int BAR_FIELD_NUMBER = 3;
    private com.dragon.proto.message.Messages.Bar bar_;
    /**
     * <code>.multimessage.Bar bar = 3;</code>
     */
    public boolean hasBar() {
      return bar_ != null;
    }
    /**
     * <code>.multimessage.Bar bar = 3;</code>
     */
    public com.dragon.proto.message.Messages.Bar getBar() {
      return bar_ == null ? com.dragon.proto.message.Messages.Bar.getDefaultInstance() : bar_;
    }
    /**
     * <code>.multimessage.Bar bar = 3;</code>
     */
    public com.dragon.proto.message.Messages.BarOrBuilder getBarOrBuilder() {
      return getBar();
    }

    public static final int BAZ_FIELD_NUMBER = 4;
    private com.dragon.proto.message.Messages.Baz baz_;
    /**
     * <code>.multimessage.Baz baz = 4;</code>
     */
    public boolean hasBaz() {
      return baz_ != null;
    }
    /**
     * <code>.multimessage.Baz baz = 4;</code>
     */
    public com.dragon.proto.message.Messages.Baz getBaz() {
      return baz_ == null ? com.dragon.proto.message.Messages.Baz.getDefaultInstance() : baz_;
    }
    /**
     * <code>.multimessage.Baz baz = 4;</code>
     */
    public com.dragon.proto.message.Messages.BazOrBuilder getBazOrBuilder() {
      return getBaz();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.dragon.proto.message.Messages.Message.Type.FOO.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (foo_ != null) {
        output.writeMessage(2, getFoo());
      }
      if (bar_ != null) {
        output.writeMessage(3, getBar());
      }
      if (baz_ != null) {
        output.writeMessage(4, getBaz());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.dragon.proto.message.Messages.Message.Type.FOO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (foo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFoo());
      }
      if (bar_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBar());
      }
      if (baz_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getBaz());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dragon.proto.message.Messages.Message)) {
        return super.equals(obj);
      }
      com.dragon.proto.message.Messages.Message other = (com.dragon.proto.message.Messages.Message) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (hasFoo() == other.hasFoo());
      if (hasFoo()) {
        result = result && getFoo()
            .equals(other.getFoo());
      }
      result = result && (hasBar() == other.hasBar());
      if (hasBar()) {
        result = result && getBar()
            .equals(other.getBar());
      }
      result = result && (hasBaz() == other.hasBaz());
      if (hasBaz()) {
        result = result && getBaz()
            .equals(other.getBaz());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasFoo()) {
        hash = (37 * hash) + FOO_FIELD_NUMBER;
        hash = (53 * hash) + getFoo().hashCode();
      }
      if (hasBar()) {
        hash = (37 * hash) + BAR_FIELD_NUMBER;
        hash = (53 * hash) + getBar().hashCode();
      }
      if (hasBaz()) {
        hash = (37 * hash) + BAZ_FIELD_NUMBER;
        hash = (53 * hash) + getBaz().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dragon.proto.message.Messages.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dragon.proto.message.Messages.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code multimessage.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:multimessage.Message)
        com.dragon.proto.message.Messages.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dragon.proto.message.Messages.Message.class, com.dragon.proto.message.Messages.Message.Builder.class);
      }

      // Construct using com.dragon.proto.message.Messages.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (fooBuilder_ == null) {
          foo_ = null;
        } else {
          foo_ = null;
          fooBuilder_ = null;
        }
        if (barBuilder_ == null) {
          bar_ = null;
        } else {
          bar_ = null;
          barBuilder_ = null;
        }
        if (bazBuilder_ == null) {
          baz_ = null;
        } else {
          baz_ = null;
          bazBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Message_descriptor;
      }

      public com.dragon.proto.message.Messages.Message getDefaultInstanceForType() {
        return com.dragon.proto.message.Messages.Message.getDefaultInstance();
      }

      public com.dragon.proto.message.Messages.Message build() {
        com.dragon.proto.message.Messages.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dragon.proto.message.Messages.Message buildPartial() {
        com.dragon.proto.message.Messages.Message result = new com.dragon.proto.message.Messages.Message(this);
        result.type_ = type_;
        if (fooBuilder_ == null) {
          result.foo_ = foo_;
        } else {
          result.foo_ = fooBuilder_.build();
        }
        if (barBuilder_ == null) {
          result.bar_ = bar_;
        } else {
          result.bar_ = barBuilder_.build();
        }
        if (bazBuilder_ == null) {
          result.baz_ = baz_;
        } else {
          result.baz_ = bazBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dragon.proto.message.Messages.Message) {
          return mergeFrom((com.dragon.proto.message.Messages.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dragon.proto.message.Messages.Message other) {
        if (other == com.dragon.proto.message.Messages.Message.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasFoo()) {
          mergeFoo(other.getFoo());
        }
        if (other.hasBar()) {
          mergeBar(other.getBar());
        }
        if (other.hasBaz()) {
          mergeBaz(other.getBaz());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dragon.proto.message.Messages.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dragon.proto.message.Messages.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.multimessage.Message.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.multimessage.Message.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.multimessage.Message.Type type = 1;</code>
       */
      public com.dragon.proto.message.Messages.Message.Type getType() {
        com.dragon.proto.message.Messages.Message.Type result = com.dragon.proto.message.Messages.Message.Type.valueOf(type_);
        return result == null ? com.dragon.proto.message.Messages.Message.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.multimessage.Message.Type type = 1;</code>
       */
      public Builder setType(com.dragon.proto.message.Messages.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.multimessage.Message.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.dragon.proto.message.Messages.Foo foo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dragon.proto.message.Messages.Foo, com.dragon.proto.message.Messages.Foo.Builder, com.dragon.proto.message.Messages.FooOrBuilder> fooBuilder_;
      /**
       * <code>.multimessage.Foo foo = 2;</code>
       */
      public boolean hasFoo() {
        return fooBuilder_ != null || foo_ != null;
      }
      /**
       * <code>.multimessage.Foo foo = 2;</code>
       */
      public com.dragon.proto.message.Messages.Foo getFoo() {
        if (fooBuilder_ == null) {
          return foo_ == null ? com.dragon.proto.message.Messages.Foo.getDefaultInstance() : foo_;
        } else {
          return fooBuilder_.getMessage();
        }
      }
      /**
       * <code>.multimessage.Foo foo = 2;</code>
       */
      public Builder setFoo(com.dragon.proto.message.Messages.Foo value) {
        if (fooBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          foo_ = value;
          onChanged();
        } else {
          fooBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.multimessage.Foo foo = 2;</code>
       */
      public Builder setFoo(
          com.dragon.proto.message.Messages.Foo.Builder builderForValue) {
        if (fooBuilder_ == null) {
          foo_ = builderForValue.build();
          onChanged();
        } else {
          fooBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.multimessage.Foo foo = 2;</code>
       */
      public Builder mergeFoo(com.dragon.proto.message.Messages.Foo value) {
        if (fooBuilder_ == null) {
          if (foo_ != null) {
            foo_ =
              com.dragon.proto.message.Messages.Foo.newBuilder(foo_).mergeFrom(value).buildPartial();
          } else {
            foo_ = value;
          }
          onChanged();
        } else {
          fooBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.multimessage.Foo foo = 2;</code>
       */
      public Builder clearFoo() {
        if (fooBuilder_ == null) {
          foo_ = null;
          onChanged();
        } else {
          foo_ = null;
          fooBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.multimessage.Foo foo = 2;</code>
       */
      public com.dragon.proto.message.Messages.Foo.Builder getFooBuilder() {
        
        onChanged();
        return getFooFieldBuilder().getBuilder();
      }
      /**
       * <code>.multimessage.Foo foo = 2;</code>
       */
      public com.dragon.proto.message.Messages.FooOrBuilder getFooOrBuilder() {
        if (fooBuilder_ != null) {
          return fooBuilder_.getMessageOrBuilder();
        } else {
          return foo_ == null ?
              com.dragon.proto.message.Messages.Foo.getDefaultInstance() : foo_;
        }
      }
      /**
       * <code>.multimessage.Foo foo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dragon.proto.message.Messages.Foo, com.dragon.proto.message.Messages.Foo.Builder, com.dragon.proto.message.Messages.FooOrBuilder> 
          getFooFieldBuilder() {
        if (fooBuilder_ == null) {
          fooBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dragon.proto.message.Messages.Foo, com.dragon.proto.message.Messages.Foo.Builder, com.dragon.proto.message.Messages.FooOrBuilder>(
                  getFoo(),
                  getParentForChildren(),
                  isClean());
          foo_ = null;
        }
        return fooBuilder_;
      }

      private com.dragon.proto.message.Messages.Bar bar_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dragon.proto.message.Messages.Bar, com.dragon.proto.message.Messages.Bar.Builder, com.dragon.proto.message.Messages.BarOrBuilder> barBuilder_;
      /**
       * <code>.multimessage.Bar bar = 3;</code>
       */
      public boolean hasBar() {
        return barBuilder_ != null || bar_ != null;
      }
      /**
       * <code>.multimessage.Bar bar = 3;</code>
       */
      public com.dragon.proto.message.Messages.Bar getBar() {
        if (barBuilder_ == null) {
          return bar_ == null ? com.dragon.proto.message.Messages.Bar.getDefaultInstance() : bar_;
        } else {
          return barBuilder_.getMessage();
        }
      }
      /**
       * <code>.multimessage.Bar bar = 3;</code>
       */
      public Builder setBar(com.dragon.proto.message.Messages.Bar value) {
        if (barBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bar_ = value;
          onChanged();
        } else {
          barBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.multimessage.Bar bar = 3;</code>
       */
      public Builder setBar(
          com.dragon.proto.message.Messages.Bar.Builder builderForValue) {
        if (barBuilder_ == null) {
          bar_ = builderForValue.build();
          onChanged();
        } else {
          barBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.multimessage.Bar bar = 3;</code>
       */
      public Builder mergeBar(com.dragon.proto.message.Messages.Bar value) {
        if (barBuilder_ == null) {
          if (bar_ != null) {
            bar_ =
              com.dragon.proto.message.Messages.Bar.newBuilder(bar_).mergeFrom(value).buildPartial();
          } else {
            bar_ = value;
          }
          onChanged();
        } else {
          barBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.multimessage.Bar bar = 3;</code>
       */
      public Builder clearBar() {
        if (barBuilder_ == null) {
          bar_ = null;
          onChanged();
        } else {
          bar_ = null;
          barBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.multimessage.Bar bar = 3;</code>
       */
      public com.dragon.proto.message.Messages.Bar.Builder getBarBuilder() {
        
        onChanged();
        return getBarFieldBuilder().getBuilder();
      }
      /**
       * <code>.multimessage.Bar bar = 3;</code>
       */
      public com.dragon.proto.message.Messages.BarOrBuilder getBarOrBuilder() {
        if (barBuilder_ != null) {
          return barBuilder_.getMessageOrBuilder();
        } else {
          return bar_ == null ?
              com.dragon.proto.message.Messages.Bar.getDefaultInstance() : bar_;
        }
      }
      /**
       * <code>.multimessage.Bar bar = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dragon.proto.message.Messages.Bar, com.dragon.proto.message.Messages.Bar.Builder, com.dragon.proto.message.Messages.BarOrBuilder> 
          getBarFieldBuilder() {
        if (barBuilder_ == null) {
          barBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dragon.proto.message.Messages.Bar, com.dragon.proto.message.Messages.Bar.Builder, com.dragon.proto.message.Messages.BarOrBuilder>(
                  getBar(),
                  getParentForChildren(),
                  isClean());
          bar_ = null;
        }
        return barBuilder_;
      }

      private com.dragon.proto.message.Messages.Baz baz_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dragon.proto.message.Messages.Baz, com.dragon.proto.message.Messages.Baz.Builder, com.dragon.proto.message.Messages.BazOrBuilder> bazBuilder_;
      /**
       * <code>.multimessage.Baz baz = 4;</code>
       */
      public boolean hasBaz() {
        return bazBuilder_ != null || baz_ != null;
      }
      /**
       * <code>.multimessage.Baz baz = 4;</code>
       */
      public com.dragon.proto.message.Messages.Baz getBaz() {
        if (bazBuilder_ == null) {
          return baz_ == null ? com.dragon.proto.message.Messages.Baz.getDefaultInstance() : baz_;
        } else {
          return bazBuilder_.getMessage();
        }
      }
      /**
       * <code>.multimessage.Baz baz = 4;</code>
       */
      public Builder setBaz(com.dragon.proto.message.Messages.Baz value) {
        if (bazBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baz_ = value;
          onChanged();
        } else {
          bazBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.multimessage.Baz baz = 4;</code>
       */
      public Builder setBaz(
          com.dragon.proto.message.Messages.Baz.Builder builderForValue) {
        if (bazBuilder_ == null) {
          baz_ = builderForValue.build();
          onChanged();
        } else {
          bazBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.multimessage.Baz baz = 4;</code>
       */
      public Builder mergeBaz(com.dragon.proto.message.Messages.Baz value) {
        if (bazBuilder_ == null) {
          if (baz_ != null) {
            baz_ =
              com.dragon.proto.message.Messages.Baz.newBuilder(baz_).mergeFrom(value).buildPartial();
          } else {
            baz_ = value;
          }
          onChanged();
        } else {
          bazBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.multimessage.Baz baz = 4;</code>
       */
      public Builder clearBaz() {
        if (bazBuilder_ == null) {
          baz_ = null;
          onChanged();
        } else {
          baz_ = null;
          bazBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.multimessage.Baz baz = 4;</code>
       */
      public com.dragon.proto.message.Messages.Baz.Builder getBazBuilder() {
        
        onChanged();
        return getBazFieldBuilder().getBuilder();
      }
      /**
       * <code>.multimessage.Baz baz = 4;</code>
       */
      public com.dragon.proto.message.Messages.BazOrBuilder getBazOrBuilder() {
        if (bazBuilder_ != null) {
          return bazBuilder_.getMessageOrBuilder();
        } else {
          return baz_ == null ?
              com.dragon.proto.message.Messages.Baz.getDefaultInstance() : baz_;
        }
      }
      /**
       * <code>.multimessage.Baz baz = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dragon.proto.message.Messages.Baz, com.dragon.proto.message.Messages.Baz.Builder, com.dragon.proto.message.Messages.BazOrBuilder> 
          getBazFieldBuilder() {
        if (bazBuilder_ == null) {
          bazBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dragon.proto.message.Messages.Baz, com.dragon.proto.message.Messages.Baz.Builder, com.dragon.proto.message.Messages.BazOrBuilder>(
                  getBaz(),
                  getParentForChildren(),
                  isClean());
          baz_ = null;
        }
        return bazBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:multimessage.Message)
    }

    // @@protoc_insertion_point(class_scope:multimessage.Message)
    private static final com.dragon.proto.message.Messages.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dragon.proto.message.Messages.Message();
    }

    public static com.dragon.proto.message.Messages.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.dragon.proto.message.Messages.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FooOrBuilder extends
      // @@protoc_insertion_point(interface_extends:multimessage.Foo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code multimessage.Foo}
   */
  public  static final class Foo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:multimessage.Foo)
      FooOrBuilder {
    // Use Foo.newBuilder() to construct.
    private Foo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Foo() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Foo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dragon.proto.message.Messages.internal_static_multimessage_Foo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dragon.proto.message.Messages.internal_static_multimessage_Foo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dragon.proto.message.Messages.Foo.class, com.dragon.proto.message.Messages.Foo.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dragon.proto.message.Messages.Foo)) {
        return super.equals(obj);
      }
      com.dragon.proto.message.Messages.Foo other = (com.dragon.proto.message.Messages.Foo) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dragon.proto.message.Messages.Foo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Foo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Foo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Foo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Foo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Foo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Foo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Foo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Foo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Foo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Foo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Foo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dragon.proto.message.Messages.Foo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code multimessage.Foo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:multimessage.Foo)
        com.dragon.proto.message.Messages.FooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Foo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Foo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dragon.proto.message.Messages.Foo.class, com.dragon.proto.message.Messages.Foo.Builder.class);
      }

      // Construct using com.dragon.proto.message.Messages.Foo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Foo_descriptor;
      }

      public com.dragon.proto.message.Messages.Foo getDefaultInstanceForType() {
        return com.dragon.proto.message.Messages.Foo.getDefaultInstance();
      }

      public com.dragon.proto.message.Messages.Foo build() {
        com.dragon.proto.message.Messages.Foo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dragon.proto.message.Messages.Foo buildPartial() {
        com.dragon.proto.message.Messages.Foo result = new com.dragon.proto.message.Messages.Foo(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dragon.proto.message.Messages.Foo) {
          return mergeFrom((com.dragon.proto.message.Messages.Foo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dragon.proto.message.Messages.Foo other) {
        if (other == com.dragon.proto.message.Messages.Foo.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dragon.proto.message.Messages.Foo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dragon.proto.message.Messages.Foo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:multimessage.Foo)
    }

    // @@protoc_insertion_point(class_scope:multimessage.Foo)
    private static final com.dragon.proto.message.Messages.Foo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dragon.proto.message.Messages.Foo();
    }

    public static com.dragon.proto.message.Messages.Foo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Foo>
        PARSER = new com.google.protobuf.AbstractParser<Foo>() {
      public Foo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Foo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Foo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Foo> getParserForType() {
      return PARSER;
    }

    public com.dragon.proto.message.Messages.Foo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:multimessage.Bar)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code multimessage.Bar}
   */
  public  static final class Bar extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:multimessage.Bar)
      BarOrBuilder {
    // Use Bar.newBuilder() to construct.
    private Bar(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bar() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Bar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dragon.proto.message.Messages.internal_static_multimessage_Bar_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dragon.proto.message.Messages.internal_static_multimessage_Bar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dragon.proto.message.Messages.Bar.class, com.dragon.proto.message.Messages.Bar.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dragon.proto.message.Messages.Bar)) {
        return super.equals(obj);
      }
      com.dragon.proto.message.Messages.Bar other = (com.dragon.proto.message.Messages.Bar) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dragon.proto.message.Messages.Bar parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Bar parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Bar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Bar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Bar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Bar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Bar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Bar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Bar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Bar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Bar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Bar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dragon.proto.message.Messages.Bar prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code multimessage.Bar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:multimessage.Bar)
        com.dragon.proto.message.Messages.BarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Bar_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Bar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dragon.proto.message.Messages.Bar.class, com.dragon.proto.message.Messages.Bar.Builder.class);
      }

      // Construct using com.dragon.proto.message.Messages.Bar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Bar_descriptor;
      }

      public com.dragon.proto.message.Messages.Bar getDefaultInstanceForType() {
        return com.dragon.proto.message.Messages.Bar.getDefaultInstance();
      }

      public com.dragon.proto.message.Messages.Bar build() {
        com.dragon.proto.message.Messages.Bar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dragon.proto.message.Messages.Bar buildPartial() {
        com.dragon.proto.message.Messages.Bar result = new com.dragon.proto.message.Messages.Bar(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dragon.proto.message.Messages.Bar) {
          return mergeFrom((com.dragon.proto.message.Messages.Bar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dragon.proto.message.Messages.Bar other) {
        if (other == com.dragon.proto.message.Messages.Bar.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dragon.proto.message.Messages.Bar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dragon.proto.message.Messages.Bar) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:multimessage.Bar)
    }

    // @@protoc_insertion_point(class_scope:multimessage.Bar)
    private static final com.dragon.proto.message.Messages.Bar DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dragon.proto.message.Messages.Bar();
    }

    public static com.dragon.proto.message.Messages.Bar getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bar>
        PARSER = new com.google.protobuf.AbstractParser<Bar>() {
      public Bar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Bar(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bar> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bar> getParserForType() {
      return PARSER;
    }

    public com.dragon.proto.message.Messages.Bar getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BazOrBuilder extends
      // @@protoc_insertion_point(interface_extends:multimessage.Baz)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code multimessage.Baz}
   */
  public  static final class Baz extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:multimessage.Baz)
      BazOrBuilder {
    // Use Baz.newBuilder() to construct.
    private Baz(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Baz() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Baz(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dragon.proto.message.Messages.internal_static_multimessage_Baz_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dragon.proto.message.Messages.internal_static_multimessage_Baz_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dragon.proto.message.Messages.Baz.class, com.dragon.proto.message.Messages.Baz.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dragon.proto.message.Messages.Baz)) {
        return super.equals(obj);
      }
      com.dragon.proto.message.Messages.Baz other = (com.dragon.proto.message.Messages.Baz) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dragon.proto.message.Messages.Baz parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Baz parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Baz parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Baz parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Baz parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dragon.proto.message.Messages.Baz parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Baz parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Baz parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Baz parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Baz parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dragon.proto.message.Messages.Baz parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dragon.proto.message.Messages.Baz parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dragon.proto.message.Messages.Baz prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code multimessage.Baz}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:multimessage.Baz)
        com.dragon.proto.message.Messages.BazOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Baz_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Baz_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dragon.proto.message.Messages.Baz.class, com.dragon.proto.message.Messages.Baz.Builder.class);
      }

      // Construct using com.dragon.proto.message.Messages.Baz.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dragon.proto.message.Messages.internal_static_multimessage_Baz_descriptor;
      }

      public com.dragon.proto.message.Messages.Baz getDefaultInstanceForType() {
        return com.dragon.proto.message.Messages.Baz.getDefaultInstance();
      }

      public com.dragon.proto.message.Messages.Baz build() {
        com.dragon.proto.message.Messages.Baz result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dragon.proto.message.Messages.Baz buildPartial() {
        com.dragon.proto.message.Messages.Baz result = new com.dragon.proto.message.Messages.Baz(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dragon.proto.message.Messages.Baz) {
          return mergeFrom((com.dragon.proto.message.Messages.Baz)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dragon.proto.message.Messages.Baz other) {
        if (other == com.dragon.proto.message.Messages.Baz.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dragon.proto.message.Messages.Baz parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dragon.proto.message.Messages.Baz) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:multimessage.Baz)
    }

    // @@protoc_insertion_point(class_scope:multimessage.Baz)
    private static final com.dragon.proto.message.Messages.Baz DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dragon.proto.message.Messages.Baz();
    }

    public static com.dragon.proto.message.Messages.Baz getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Baz>
        PARSER = new com.google.protobuf.AbstractParser<Baz>() {
      public Baz parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Baz(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Baz> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Baz> getParserForType() {
      return PARSER;
    }

    public com.dragon.proto.message.Messages.Baz getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multimessage_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multimessage_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multimessage_Foo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multimessage_Foo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multimessage_Bar_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multimessage_Bar_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multimessage_Baz_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_multimessage_Baz_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016multimsg.proto\022\014multimessage\"\266\001\n\007Messa" +
      "ge\022(\n\004type\030\001 \001(\0162\032.multimessage.Message." +
      "Type\022\036\n\003foo\030\002 \001(\0132\021.multimessage.Foo\022\036\n\003" +
      "bar\030\003 \001(\0132\021.multimessage.Bar\022\036\n\003baz\030\004 \001(" +
      "\0132\021.multimessage.Baz\"!\n\004Type\022\007\n\003FOO\020\000\022\007\n" +
      "\003BAR\020\001\022\007\n\003BAZ\020\002\"\023\n\003Foo\022\014\n\004name\030\001 \001(\t\"\023\n\003" +
      "Bar\022\014\n\004name\030\001 \001(\t\"\023\n\003Baz\022\014\n\004name\030\001 \001(\tBC" +
      "\n\030com.dragon.proto.messageB\010Messages\252\002\034G" +
      "oogle.Protobuf.Multimessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_multimessage_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_multimessage_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multimessage_Message_descriptor,
        new java.lang.String[] { "Type", "Foo", "Bar", "Baz", });
    internal_static_multimessage_Foo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_multimessage_Foo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multimessage_Foo_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_multimessage_Bar_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_multimessage_Bar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multimessage_Bar_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_multimessage_Baz_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_multimessage_Baz_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_multimessage_Baz_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
